#FROM redis:3.2-alpine
FROM redis:5.0.7-alpine

#CMD touch /var/log/redis/redis-server.log
#CMD chmod 777 /var/log/redis/redis-server.log

#COPY redis.conf /usr/local/etc/redis/redis.conf
#CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]



EXPOSE 6379